logger :
  level: Trace # уровень логгирования - какие события будут записываться, а какие нет
  syslog: false # нужно ли записывать логи приложения в файл с ситсемными логами
  output: server.log # имя файла для записи логов 

server:
  address: '127.0.0.1:8080'